SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS class_students_courses_approval;
DROP TABLE IF EXISTS class_students;
DROP TABLE IF EXISTS class_courses;
DROP TABLE IF EXISTS classes;
DROP TABLE IF EXISTS documents;
DROP TABLE IF EXISTS video_completion;
DROP TABLE IF EXISTS course_enrollments;
DROP TABLE IF EXISTS quiz_answers;
DROP TABLE IF EXISTS quiz_attempts;
DROP TABLE IF EXISTS quiz_options;
DROP TABLE IF EXISTS quiz_questions;
DROP TABLE IF EXISTS quizzes;
DROP TABLE IF EXISTS videos;
DROP TABLE IF EXISTS chapters;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS users;

SET FOREIGN_KEY_CHECKS = 1;
